require({
	paths:{
		"jquery":"./js/jquery",
		"text":"./js/require.text",
		"frag":"./frag",
	},
	shim:{
		"jquery":{
			"exports":"jQuery"
		}
	}
},[
	"module",
	"jquery",
	"./api/parsedoc.js",
	"./js/kbd",
	"./js/ui",
	"./js/request",
	"./js/session",
	"./js/objutils"//,
	//"text!frag/doc.html"
],function(
	module,
	_$,
	parsedoc,
	kbd,
	ui,
	r,
	session,
	objutils,
	//frag_doc
){
	window.objutils=objutils;
	$=_$.noConflict();
	//$(document.body).html(frag_doc)
	window.buildClient=function(){
		var obj={};
		if(r.tojson().parameters.jsondata){
			$.getJSON(r.tojson().parameters.jsondata,function(obj){
				window.obj=obj;
				ui({target:$("#output"),root:obj});
			});
		}else{
			$.getJSON("https://raw.githubusercontent.com/evocert/kwe/main/gendocs/codedefs.json",function(obj){
				window.obj=obj;
				ui({target:$("#output"),root:obj});
			});
		}
	};
	window.buildClient();
});
